#!/bin/bash
set -e

r() { tput setaf 1; tput bold; }
g() { tput setaf 2; tput bold; }
c() { tput sgr0; }
error() { echo "$(r)Error$(c): $*" >&2; }
success() { echo "$(g)Success$(c): $*" >&2; }

handler() {
	error 'Failed to install!'
}

[[ -z $1 ]] && error 'Please provide a repository name for the keystore!' && exit 1

trap handler EXIT SIGINT SIGQUIT SIGTERM

DIR="$(dirname "$(readlink -f "$0")")"
if uname -a | grep -q darwin; then
	grep -q "$DIR" ~/.bash_profile || echo "PATH=$DIR:"'$PATH' >> ~/.bash_profile
else
	grep -q "$DIR" ~/.bashrc || echo "PATH=$DIR:"'$PATH' >> ~/.bashrc
fi

[[ -f ~/.zshrc ]] && ! grep -q "$DIR" ~/.zshrc && echo "PATH=$DIR:"'$PATH' >> ~/.zshrc

$DIR/secnotes -s $1
$DIR/secnotes -g

echo "$(tput setaf 2; tput bold)Success$(tput sgr0): Run 'secnotes' from anywhere to use the tool!"
trap - EXIT